"""change original_url to text

Revision ID: 820c0fe021ac
Revises: c2fb340c9d69
Create Date: 2026-07-16 22:46:17.716294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820c0fe021ac'
down_revision = 'c2fb340c9d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_urls', schema=None) as batch_op:
        batch_op.alter_column('original_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_urls', schema=None) as batch_op:
        batch_op.alter_column('original_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
