"""initial tables

Revision ID: c2fb340c9d69
Revises: 
Create Date: 2026-05-11 23:07:04.918885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fb340c9d69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('short_urls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_clicks', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('short_urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_short_urls_click_count'), ['click_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_urls_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_short_urls_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_urls_user_id'), ['user_id'], unique=False)

    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('user_agent_raw', sa.String(length=500), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['short_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clicks_clicked_at'), ['clicked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index('ix_clicks_url_country', ['url_id', 'country'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_url_id'), ['url_id'], unique=False)
        batch_op.create_index('ix_clicks_url_time', ['url_id', 'clicked_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_index('ix_clicks_url_time')
        batch_op.drop_index(batch_op.f('ix_clicks_url_id'))
        batch_op.drop_index('ix_clicks_url_country')
        batch_op.drop_index(batch_op.f('ix_clicks_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_clicks_clicked_at'))

    op.drop_table('clicks')
    with op.batch_alter_table('short_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_urls_user_id'))
        batch_op.drop_index('ix_short_urls_user_active')
        batch_op.drop_index(batch_op.f('ix_short_urls_slug'))
        batch_op.drop_index(batch_op.f('ix_short_urls_click_count'))

    op.drop_table('short_urls')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_api_key'))

    op.drop_table('users')
    # ### end Alembic commands ###
